typography_spectrum: 0.015386416106438726
color:
  saturation: 0.5098992092212165
  brandStrength: 0.6894309682280084
  rhythmicContrast: 0.811784581720995
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#725700'
    - '#FC2E8D'
    - '#E6B600'
  lightness: 0.017951915895769208
github: true
layout_spectrum: 0.8206606353949386
analytics:
  google: UA-79126334-1
author:
  email: ksvarre@gmail.com
  name: Kristoffer R. Svarre
  url: www.linkedin.com/in/ksvarre
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/51a61f8a-cff4-42cc-bbb4-4ea5beb5b733.png
name: Think Like Me
navigation:
  - name: Technology & Science
    url: 'http://ai.think-like.me'
    type: external
  - name: Motivation & Personal Development
    url: 'http://development.think-like.me'
    type: external
  - name: 'Business, Innovation & Entrepreneurship'
    url: 'http://business.think-like.me'
    type: external
  - name: About me
    url: 'https://www.linkedin.com/in/ksvarre'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b9e985e1-7831-41ec-aba7-58fabf799d41.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Think Like Me!
content: []
description: welcome to my blog. i will post about things i find interesting. enjoy.
purpose: []
