typography_spectrum: 0.36434033303521574
color:
  saturation: 0.35632035811431706
  brandStrength: 0.020719361025840044
  lightness: 0.42442902317270637
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  rhythmicContrast: 0.34971131896600127
layout_spectrum: 0.9881068337708712
author:
  email: ksvarre@gmail.com
  name: Kristoffer R. Svarre
name: Personaleurship
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: What I Would Like You to Know
