author:
  email: ksvarre@gmail.com
  name: Kristoffer R. Svarre
  url: www.linkedin.com/in/ksvarre
title: What I Would Like You to Know
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
color:
  saturation: 0.2258064
  brandStrength: 0.5
  lightness: 1
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  rhythmicContrast: 0.2598566
typography_spectrum: 0.8133163116872311
navigation:
  - name: 'https://www.linkedin.com/in/ksvarre'
    url: LinkedIn Profile
    type: external
layout_spectrum: 0.5591398
analytics:
  google: UA-79126334-1
name: Personaleurship
