typography_spectrum: 0.36434033303521574
color:
  saturation: 0.7655318067409098
  brandStrength: 0.6261494064237922
  lightness: 0.4201720857527107
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  rhythmicContrast: 0.4085321119055152
layout_spectrum: 0.6014146069064736
author:
  email: ksvarre@gmail.com
  name: Kristoffer R. Svarre
name: Personaleurship
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: What I Would Like You to Know
