layout_spectrum: 0.1398878068037995
typography_spectrum: 0.014979760307671116
color:
  saturation: 0.5042431323378725
  brandStrength: 0.6850068103759043
  rhythmicContrast: 0.8155349829473008
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#725700'
    - '#FC2E8D'
    - '#E6B600'
  lightness: 0.01198749865700334
github: true
analytics:
  google: UA-79126334-1
author:
  email: ksvarre@gmail.com
  name: Kristoffer R. Svarre
  url: www.linkedin.com/in/ksvarre
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/51a61f8a-cff4-42cc-bbb4-4ea5beb5b733.png
name: Think Like Me
navigation:
  - name: Technology & Science
    url: 'http://ai.think-like.me'
    type: external
  - name: Motivation & Personal Development
    url: 'http://development.think-like.me'
    type: external
  - name: 'Business, Innovation & Entrepreneurship'
    url: 'http://business.think-like.me'
    type: external
  - name: About me
    url: 'https://www.linkedin.com/in/ksvarre'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b9e985e1-7831-41ec-aba7-58fabf799d41.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Think Like Me!
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/fe365cf84c8abe5049098b954f9bfc9f161b46d9.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/fe365cf84c8abe5049098b954f9bfc9f161b46d9.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/83210574985e92d186111feacad259b2/noop.jpg?input=https%3A%2F%2Fwww.wired.com%2Fwp-content%2Fuploads%2F2016%2F11%2FXZ_ParticleCollision_1K.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: welcome to my blog. i will post about things i find interesting. enjoy.
purpose: []
