typography_spectrum: 0.36434033303521574
color:
  saturation: 0.30597560736350715
  brandStrength: 0.6455900487489998
  lightness: 0.023472424130886793
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  rhythmicContrast: 0.6318233923520893
layout_spectrum: 0.6014146069064736
author:
  email: ksvarre@gmail.com
  name: Kristoffer R. Svarre
name: Personaleurship
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: What I Would Like You to Know
