author:
  email: ksvarre@gmail.com
  name: Kristoffer R. Svarre
  url: www.linkedin.com/in/ksvarre
title: What I Would Like You to Know
name: Personaleurship
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: ''
color:
  saturation: 0.6415771
  brandStrength: 0.02071936102584004
  lightness: 1
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  rhythmicContrast: 0.483871
typography_spectrum: 0.8133163116872311
layout_spectrum: 0.8996416
navigation:
  - name: 'https://www.linkedin.com/in/ksvarre'
    url: LinkedIn Profile
    type: external
analytics:
  google: UA-79126334-1
